apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argo-cd-argocd-server
  namespace: argo-cd
spec:
  gateways:
  - gateway/istio-ingressgateway
  hosts:
  - localhost
  - host.docker.internal
  http:
  - match:
    - uri:
        prefix: /argocd/
    name: http
    rewrite:
      uri: /argocd/
    route:
    - destination:
        host: argo-cd-argocd-server.argo-cd.svc.cluster.local
        port:
          number: 443
        subset: https
      weight: 100
